POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJfMSIsImlkIjoiNjFhMjMxMjMzMWUzNWNlN2ZkNTg5ZTYyIiwiaWF0IjoxNjM4MDMxNzQxLCJleHAiOjE2MzgwMzUzNDF9.8g-vBC7wiZHbJCSqW2bLCIUvbJodVTl_LEAdZw_OS-o

{
    "title": "Is this written by user-1?",
    "author": "User 1",
    "url": "testing.url",
    "likes": 5
}